# to make a normal K8-manifest.yaml file into HELM then we have to use CHART.YAML

apiVersion: v2
name: nginx
version: 0.1.3 # This is Helm Chart version
description: upgrading to 1.31.3-alpine
appVersion: 1.31.3-alpine # application version nginx version